mies/mies/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import views as usuario_views
from red import views as red_views
from empleado import views as empleado_views
from ubicacion import views as ubicacion_views
from practica import views as practica_views
from actividad import views as actividad_views
from capacitacion import views as capacitacion_views
from inventario import views as inventario_views
from custodia import views as custodia_views
from configuracion import views as configuracion_views
from django.conf import settings
from django.conf.urls.static import static
#400
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [

    path('admin/', admin.site.urls),
    #MENU PARA LOS USUARIOS
    path('', usuario_views.dashboard_view.as_view(), name="dashboard") ,
   
    #MODULO OTROS
    # ACCESO A REDES  
    path('AccesoRed', red_views.AccesoRedListView.as_view(), name="accesoRed_listar") ,
    path('AccesoRed/Crear', red_views.AccesoRedCreateView.as_view(), name="accesoRed_crear") ,
    path('AccesoRed/Excel', red_views.AccesoRedExcelListView.as_view(), name="accesoRedExcel_crear") ,
    path('AccesoRed/Editar/<int:pk>', red_views.AccesoRedUpdateView.as_view(), name="accesoRed_editar") ,
    path('AccesoRed/Eliminar/<int:pk>', red_views.AccesoRedDeleteView.as_view(), name="accesoRed_eliminar") ,
    path('AccesoRed/Detalle/<int:pk>', red_views.AccesoRedDetailView.as_view(), name="accesoRed_detalle") ,
    #MODULO DE EMPLEADO
    #-- empleado
    path('Empleado', empleado_views.EmpleadoListView.as_view(), name="empleado_listar") ,
    path('Empleado/Crear', empleado_views.EmpleadoCreateView.as_view(), name="empleado_crear") ,
    path('Empleado/Excel', empleado_views.EmpleadoExcelListView.as_view(), name="empleadoExcel_crear") ,
    path('Empleado/Editar/<int:pk>', empleado_views.EmpleadoUpdateView.as_view(), name="empleado_editar") ,
    path('Empleado/Eliminar/<int:pk>', empleado_views.EmpleadoDeleteView.as_view(), name="empleado_eliminar") ,
    path('Empleado/Detalle/<int:pk>', empleado_views.EmpleadoDetailView.as_view(), name="empleado_detalle") ,
    #--area
    path('Area', empleado_views.AreaListView.as_view(), name="area_listar") ,
    path('Area/Crear', empleado_views.AreaCreateView.as_view(), name="area_crear") ,
    path('Area/Editar/<int:pk>', empleado_views.AreaUpdateView.as_view(), name="area_editar") ,
    path('Area/Eliminar/<int:pk>', empleado_views.AreaDeleteView.as_view(), name="area_eliminar") ,
    path('Area/Detalle/<int:pk>', empleado_views.AreaDetailView.as_view(), name="area_detalle") ,
    #--cargo
    path('Cargo', empleado_views.CargoListView.as_view(), name="cargo_listar") ,
    path('Cargo/Crear', empleado_views.CargoCreateView.as_view(), name="cargo_crear") ,
    path('Cargo/Editar/<int:pk>', empleado_views.CargoUpdateView.as_view(), name="cargo_editar") ,
    path('Cargo/Eliminar/<int:pk>', empleado_views.CargoDeleteView.as_view(), name="cargo_eliminar") ,
    path('Cargo/Detalle/<int:pk>', empleado_views.CargoDetailView.as_view(), name="cargo_detalle") ,
    #--unidad de atencion
    path('UnidadAtencion', empleado_views.UnidadListView.as_view(), name="unidad_listar") ,
    path('UnidadAtencion/Crear', empleado_views.UnidadCreateView.as_view(), name="unidad_crear") ,
    path('UnidadAtencion/Editar/<int:pk>', empleado_views.UnidadUpdateView.as_view(), name="unidad_editar") ,
    path('UnidadAtencion/Eliminar/<int:pk>', empleado_views.UnidadDeleteView.as_view(), name="unidad_eliminar") ,
    path('UnidadAtencion/Detalle/<int:pk>', empleado_views.UnidadDetailView.as_view(), name="unidad_detalle") ,
    #MODULO UBICACION DISTRITAL
    #--zona
    path('Zona', ubicacion_views.ZonaListView.as_view(), name="zona_listar") ,
    path('Zona/Crear', ubicacion_views.ZonaCreateView.as_view(), name="zona_crear") ,
    path('Zona/Editar/<int:pk>', ubicacion_views.ZonaUpdateView.as_view(), name="zona_editar") ,
    path('Zona/Eliminar/<int:pk>', ubicacion_views.ZonaDeleteView.as_view(), name="zona_eliminar") ,
    path('Zona/Detalle/<int:pk>', ubicacion_views.ZonaDetailView.as_view(), name="zona_detalle") ,
    #--provincia
    path('Provincia', ubicacion_views.ProvinciaListView.as_view(), name="provincia_listar") ,
    path('Provincia/Crear', ubicacion_views.ProvinciaCreateView.as_view(), name="provincia_crear") ,
    path('Provincia/Editar/<int:pk>', ubicacion_views.ProvinciaUpdateView.as_view(), name="provincia_editar") ,
    path('Provincia/Eliminar/<int:pk>', ubicacion_views.ProvinciaDeleteView.as_view(), name="provincia_eliminar") ,
    path('Provincia/Detalle/<int:pk>', ubicacion_views.ProvinciaDetailView.as_view(), name="provincia_detalle") ,
    #--distrito
    path('Distrito', ubicacion_views.DistritoListView.as_view(), name="distrito_listar") ,
    path('Distrito/Crear', ubicacion_views.DistritoCreateView.as_view(), name="distrito_crear") ,
    path('Distrito/Editar/<int:pk>', ubicacion_views.DistritoUpdateView.as_view(), name="distrito_editar") ,
    path('Distrito/Eliminar/<int:pk>', ubicacion_views.DistritoDeleteView.as_view(), name="distrito_eliminar") ,
    path('Distrito/Detalle/<int:pk>', ubicacion_views.DistritoDetailView.as_view(), name="distrito_detalle") ,
    #MODULO PRACTICAS PROFESIONALIZANTES
    #--Pasante
    path('Pasante', practica_views.PasanteListView.as_view(), name="pasante_listar") ,
    path('Pasante/Crear', practica_views.PasanteCreateView.as_view(), name="pasante_crear") ,
    path('Pasante/Excel', practica_views.PasanteExcelListView.as_view(), name="pasanteExcel_crear") ,
    path('Pasante/Editar/<int:pk>', practica_views.PasanteUpdateView.as_view(), name="pasante_editar") ,
    path('Pasante/Eliminar/<int:pk>', practica_views.PasanteDeleteView.as_view(), name="pasante_eliminar") ,
    path('Pasante/Detalle/<int:pk>', practica_views.PasanteDetailView.as_view(), name="pasante_detalle") ,
    #--Carrera
    path('Carrera', practica_views.CarreraListView.as_view(), name="carrera_listar") ,
    path('Carrera/Crear', practica_views.CarreraCreateView.as_view(), name="carrera_crear") ,
    path('Carrera/Editar/<int:pk>', practica_views.CarreraUpdateView.as_view(), name="carrera_editar") ,
    path('Carrera/Eliminar/<int:pk>', practica_views.CarreraDeleteView.as_view(), name="carrera_eliminar") ,
    path('Carrera/Detalle/<int:pk>', practica_views.CarreraDetailView.as_view(), name="carrera_detalle") ,
    #--Universidad
    path('Universidad', practica_views.UniversidadListView.as_view(), name="universidad_listar") ,
    path('Universidad/Crear', practica_views.UniversidadCreateView.as_view(), name="universidad_crear") ,
    path('Universidad/Editar/<int:pk>', practica_views.UniversidadUpdateView.as_view(), name="universidad_editar") ,
    path('Universidad/Eliminar/<int:pk>', practica_views.UniversidadDeleteView.as_view(), name="universidad_eliminar") ,
    path('Universidad/Detalle/<int:pk>', practica_views.UniversidadDetailView.as_view(), name="universidad_detalle") ,
    

    #MODULO ACTIVIDAD
    #--Actividad
    path('Actividad', actividad_views.ActividadListView.as_view(), name="actividad_listar"),
    path('Actividad/Crear',actividad_views.ActividadCreateView.as_view(),name ="actividad_crear"),
    path('Actividad/pdf/<int:pk>', actividad_views.ActividadReportePdfDetailView.as_view(), name="actividad_reporte_pdf") ,
    path('Actividad/Editar/<int:pk>',actividad_views.ActividadUpdateView.as_view(),name ="actividad_editar"),
    path('Actividad/Eliminar/<int:pk>',actividad_views.ActividadDeleteView.as_view(),name ="actividad_eliminar"),
    path('Actividad/Detalle/<int:pk>',actividad_views.ActividadDetailView.as_view(),name ="actividad_detalle"),
   
    #--Asunto
    path('Asunto', actividad_views.AsuntoListView.as_view(), name="asunto_listar"),
    path('Asunto/Crear',actividad_views.AsuntoCreateView.as_view(),name ="asunto_crear"),
    path('Asunto/Editar/<int:pk>',actividad_views.AsuntoUpdateView.as_view(),name ="asunto_editar"),
    path('Asunto/Eliminar/<int:pk>',actividad_views.AsuntoDeleteView.as_view(),name ="asunto_eliminar"),
    path('Asunto/Detalle/<int:pk>',actividad_views.AsuntoDetailView.as_view(),name ="asunto_detalle"),

     #--Capacitacion
    path('Capacitacion', capacitacion_views.CapacitacionListView.as_view(), name="capacitacion_listar") ,
    path('Capacitacion/Crear', capacitacion_views.CapacitacionCreateView.as_view(), name="capacitacion_crear") ,
    path('Capacitacion/Editar/<int:pk>', capacitacion_views.CapacitacionUpdateView.as_view(), name="capacitacion_editar") ,
    path('Capacitacion/Eliminar/<int:pk>', capacitacion_views.CapacitacionDeleteView.as_view(), name="capacitacion_eliminar") ,
    path('Capacitacion/Detalle/<int:pk>', capacitacion_views.CapacitacionDetailView.as_view(), name="capacitacion_detalle") ,
    path('Capacitacion/pdf/<int:pk>', capacitacion_views.CapacitacionReportePdfDetailView.as_view(), name="capacitacion_reporte_pdf") ,


    #Modulo Inventario 
    #--Marca
    path('Marca', inventario_views.MarcaListView.as_view(), name="marca_listar"),
    path('Marca/Crear',inventario_views.MarcaCreateView.as_view(),name ="marca_crear"),
    path('Marca/Editar/<int:pk>',inventario_views.MarcaUpdateView.as_view(),name ="marca_editar"),
    path('Marca/Eliminar/<int:pk>',inventario_views.MarcaDeleteView.as_view(),name ="marca_eliminar"),
    path('Marca/Detalle/<int:pk>',inventario_views.MarcaDetailView.as_view(),name ="marca_detalle"),
    #--Modelo
    path('Modelo', inventario_views.ModeloListView.as_view(), name="modelo_listar"),
    path('Modelo/Crear',inventario_views.ModeloCreateView.as_view(),name ="modelo_crear"),
    path('Modelo/Editar/<int:pk>',inventario_views.ModeloUpdateView.as_view(),name ="modelo_editar"),
    path('Modelo/Eliminar/<int:pk>',inventario_views.ModeloDeleteView.as_view(),name ="modelo_eliminar"),
    path('Modelo/Detalle/<int:pk>',inventario_views.ModeloDetailView.as_view(),name ="modelo_detalle"),

mies/empleado/models.py
from django.db import models
from ubicacion.models import Distrito
import os
from django.db.models.signals import pre_delete, post_delete, pre_save
from django.conf import settings
from django.dispatch import receiver
# Modelos del modulo empleado.
#modelo AREA
class Area(models.Model):
    """Model definition for area."""
    distrito = models.ForeignKey(Distrito, on_delete=models.PROTECT)
    descripcion = models.CharField('Area', max_length=50, unique=True)

    class Meta:
        """Meta definition for area."""

        verbose_name = 'area'
        verbose_name_plural = 'areas'

    def __str__(self):
        """Unicode representation of area."""
        return self.descripcion

    def save(self, *args, **kwargs):
        """Save method for Area."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Area, self).save(*args, **kwargs)

#modelo CARGO
class Cargo(models.Model):
    """Model definition for Cargo."""

    descripcion = models.CharField('Cargo', max_length=100, unique=True)

    class Meta:
        """Meta definition for Cargo."""

        verbose_name = 'Cargo'
        verbose_name_plural = 'Cargos'

    def __str__(self):
        """Unicode representation of Cargo."""
        return self.descripcion

    def save(self, *args, **kwargs):
        """Save method for Cargo."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Cargo, self).save(*args, **kwargs)

 #modelo UNIDAD DE ATENCION   
class UnidadAtencion(models.Model):
    """Model definition for UnidadAtencion."""

    descripcion = models.CharField('Unidad de Atención', max_length=50, unique =True)
    codigo = models.CharField('Código Unidad de Atención', max_length=50, unique =True)

    class Meta:
        """Meta definition for UnidadAtencion."""

        verbose_name = 'Unidad de Atención'
        verbose_name_plural = 'Unidad de Atenciones'

    def __str__(self):
        """Unicode representation of UnidadAtencion."""
        return ("{}-{}").format(self.descripcion,self.codigo)

    def save(self, *args, **kwargs):
        """Save method for UnidadAtencion."""
        self.descripcion =self.descripcion and (self.descripcion).upper()
        return super(UnidadAtencion, self).save(*args, **kwargs)

#modelo EMPLEADO
class Empleado(models.Model):
    """Model definition for Empleado."""
    area = models.ForeignKey(Area, on_delete=models.PROTECT)
    cargo = models.ForeignKey(Cargo, on_delete=models.PROTECT)
    unidadAtencion = models.ForeignKey(UnidadAtencion,verbose_name='Unidad de Atención',on_delete=models.PROTECT, null=True , blank= True)
    nombres = models.CharField('Nombres', max_length=50)
    apellidos = models.CharField('Apellidos', max_length=50)
    lista_genero = [
    ('1', 'MASCULINO'),
    ('2', 'FEMENINO'),
    ('3', 'GLBTI'),]
    genero = models.CharField('Género',max_length=1, choices=lista_genero, default='2')
    correo = models.EmailField('Correo', max_length=254, unique= True)
    cedula = models.CharField('Cédula', max_length=10, null=True, blank=True, unique = True)
    telefono = models.CharField('Télefono móvil', max_length=10, null=True, blank=True)
    foto = models.ImageField('Foto', upload_to='Empleados/', height_field=None, width_field=None, max_length=None,null=True,blank=True)
    estado = models.BooleanField('Empleado está activo', default = True)
    class Meta:
        """Meta definition for Empleado."""

        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def __str__(self):
        """Unicode representation of Empleado."""
        return ("{} {}").format(self.apellidos, self.nombres)

    def save(self, *args, **kwargs):
        """Save method for Empleado."""
        self.nombres = self.nombres and (self.nombres).upper()
        self.apellidos = self.apellidos and (self.apellidos).upper() 
        self.correo =self.correo and (self.correo).upper()
        return super(Empleado, self).save(*args, **kwargs)

@receiver(post_delete, sender=Empleado)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    ruta = settings.MEDIA_ROOT +"\\"+ str(instance.foto)
    print(ruta)
    if ruta:
        if os.path.isfile(ruta):
            os.remove(ruta)
@receiver(pre_save, sender=Empleado)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = Empleado.objects.get(pk=instance.pk).foto
    except Empleado.DoesNotExist:
        return False

    new_file = instance.foto
    if not old_file == new_file:
        ruta = settings.MEDIA_ROOT +"\\"+ str(old_file)
        if os.path.isfile(ruta):
            os.remove(ruta)

mies/ubicacion/models.py
from django.db import models

# Create your models here.
class Zona(models.Model):
    """Model definition for Zona."""

    descripcion = models.CharField('Zona', max_length=50, unique=True)

    class Meta:
        """Meta definition for Zona."""

        verbose_name = 'Zona'
        verbose_name_plural = 'Zonas'

    def __str__(self):
        return self.descripcion

    def save(self, *args, **kwargs):
        """Save method for Zona."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Zona, self).save(*args, **kwargs)


class Provincia(models.Model):
    """Model definition for Provincia."""
    zona = models.ForeignKey(Zona, on_delete=models.PROTECT)
    descripcion = models.CharField('Provincia', max_length=50, unique=True)

    class Meta:
        """Meta definition for Provincia."""

        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    def __str__(self):
        return self.descripcion
    
    def save(self, *args, **kwargs):
        """Save method for Provincia."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Provincia, self).save(*args, **kwargs)


class Distrito(models.Model):
    """Model definition for Distrito."""
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion = models.CharField('Distrito', max_length=50, unique=True)
    alias = models.CharField('Alias Distrito', max_length=50, unique=True)

    class Meta:
        """Meta definition for Distrito."""

        verbose_name = 'Distrito'
        verbose_name_plural = 'Distritos'

    def __str__(self):
        """Unicode representation of Distrito."""
        return self.descripcion

    
    def save(self, *args, **kwargs):
        """Save method for Distrito."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        self.alias = self.alias and (self.alias).upper()
        return super(Distrito, self).save(*args, **kwargs)

mies/templates/empleado/area_listado.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %}ÁREA{% endblock title %}


{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        
        <li class="breadcrumb-item"><a href="{% url 'empleado_listar' %}">Empleado</a></li>
        <li class="breadcrumb-item active" aria-current="page">Área</li>
    </ol>
</nav>
<div class="container-fluid">
    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row ">
                <div class="col">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de Áreas</h6>
                </div>
                <div class="col  ">
                    {% if perms.empleado.add_area %}
                    <div class="float-right">
                        <a class="btn btn-secondary btn-sm" href="{% url 'area_crear'%}" role="button"> Nuevo</a>

                    </div>
                    {% endif %}


                </div>
            </div>

        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><b>ÁREA</b></th>
                            <th><b>DISTRITO</b></th>
                            <th><b>ACCIONES</b></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for area in object_list %}
                        <tr>
                            <td>{{ area.descripcion }}</td>
                            <td>{{ area.distrito }}</td>


                            <td>
                                <a data-toggle="popover" title="Ver" class="btn btn-light btn-sm "
                                    onclick="abrirModalDetalle('{% url 'area_detalle' area.id%}')"> <i
                                        data-toggle="popover" title="Ver" class="fa fa-eye"></i>
                                </a>

                                {% if perms.empleado.change_area %}
                                <button data-toggle="popover" title="Editar" id="modalEditarZona"
                                    class="btn btn-light btn-sm"
                                    onclick="abrirModalEditar('{% url 'area_editar' area.id%}')"> <i
                                        data-toggle="popover" title="Editar" class="fa fa-edit"></i>
                                </button>
                                {% endif %}


                                {% if perms.empleado.delete_area %}
                                <a data-toggle="popover" title="Eliminar" class="btn btn-light btn-sm"
                                    onclick="abrirModalEliminar('{% url 'area_eliminar' area.id%}')"><i
                                        data-toggle="popover" title="Eliminar" class="fa fa-trash"></i>
                                </a>
                                {% endif %}

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>


<!-- Modal Editar -->
<div class="modal fade" id="editar" role="dialog">

</div>

<!-- Modal Eliminar -->
<div class="modal fade" id="eliminar" role="dialog">

</div>

<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="detalle" aria-hidden="true">

</div>


{% endblock content_main%}


{% block content_extra_js %}
{% endblock content_extra_js %}

mies/templates/empleado/empleado_listado.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %}ACCESO EMPLEADO {% endblock title %}


{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Empleado</li>
    </ol>
</nav>

<div class="container-fluid">
    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row ">
                <div class="col">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de empleados</h6>
                </div>
                <div class="col-md-4">
                    <div class="dropdown float-right">
                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Configuraciones
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                            {% if perms.ubicacion.view_zona %}
                            <a class="dropdown-item " href="{% url 'zona_listar'%}">
                                Zona</a>
                            {% endif %}
                                
                            
                            {% if perms.ubicacion.view_provincia %}
                            <a class="dropdown-item " href="{% url 'provincia_listar'%}">
                                Provincia</a>
                            {% endif %}
                                
                            
                            {% if perms.ubicacion.view_distrito %}
                            <a class="dropdown-item " href="{% url 'distrito_listar'%}">
                                Distrito</a>
                            {% endif %}
                            
                                                    
                        {% if perms.empleado.view_area %}
                        <a class="dropdown-item " href="{% url 'area_listar'%}">
                            Área</a>
                        {% endif %}
                            
                        
                        {% if perms.empleado.view_cargo %}
                        <a class="dropdown-item " href="{% url 'cargo_listar'%}">
                            Cargo</a>
                        {% endif %}
                            
                        
                        {% if perms.empleado.view_unidadatencion %}
                        <a class="dropdown-item " href="{% url 'unidad_listar'%}">
                            Unidad de Atención</a>
                        {% endif %}
                           
                
                        </div>
                    </div>
                </div>
                
                <div class="col-md-2 ">
                    <div class="dropdown float-right">
                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Acciones
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                            {% if perms.empleado.add_empleado %}
                            <a class="dropdown-item" href="{% url 'empleado_crear'%}">Nuevo Empleado</a>

                            {% endif %}
                            <a class="dropdown-item" href="{% url 'empleadoExcel_crear'%}">Reporte Excel</a>


                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm" id="dataTable" width="100%" cellspacing="0" >
                    <thead>
                        <tr >

                            <th><b>ÁREA</b></th>
                            <th ><b>CARGO</b></th>
                            <th ><b>UNIDAD DE ATENCIÓN</b></th>
                            <th><b>NOMBRES</b></th>
                           
                            <th><b>GÉNERO</b></th>
                            <th><b>CORREO</b></th>
                            <th><b>CÉDULA</b></th>
                            <th><b>TELÉFONO MÓVIL</b></th>
                            <th><b>ESTADO</b></th>
                            <th><b>ACCIONES</b></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empl in object_list %}
                        <tr>

                     
                            <td>{{ empl.area }}</td>
                            <td>{{ empl.cargo }}</td>
                            <td>
                                {% if empl.unidadAtencion is none %}
                                <p>N/A</p>
                                {% else %}
                                {{ empl.unidadAtencion }}
                                {% endif%}
                            </td>
                            <td >{{ empl.apellidos }} {{ empl.nombres }}</td>
                         
                            <td>
                                {% if empl.genero == '1' %}
                                <p>MASCULINO</p>
                                {% elif empl.genero == '2' %}
                                <p>FEMENINO</p>
                                {% else %}
                                <p>LGTBI</p>
                                {% endif%}
                            </td>
                            <td>{{ empl.correo }}</td>
                            <td>{{ empl.cedula }}</td>
                            <td>
                                {% if empl.telefono is none %}
                                <p>N/A</p>
                                {% else %}
                                {{ empl.telefono }}
                                {% endif%}
                            </td>
                            <td>
                                {% if empl.estado%}
                                <span class="badge badge-success">Activo</span>
                                {% else %}
                                <span class="badge badge-danger">No Activo</span>
                                {% endif %}

                            </td>
                            <td>
                                <a class="btn btn-light btn-sm "
                                    onclick="abrirModalDetalle('{% url 'empleado_detalle' empl.id%}')"> <i
                                        class="fa fa-eye"></i>
                                </a>

                                {% if perms.empleado.change_empleado %}
                                <button id="modalEditarAccesoRed" class="btn btn-light btn-sm"
                                    onclick="abrirModalEditar('{% url 'empleado_editar' empl.id%}')"> <i
                                        class="fa fa-edit"></i>
                                </button>
                                {% endif %}


                                {% if perms.empleado.delete_empleado %}
                                <button id="modalEliminarAccesoRed" class="btn btn-light btn-sm"
                                    onclick="abrirModalEliminar('{% url 'empleado_eliminar' empl.id%}')"> <i
                                        class="fa fa-trash"></i>
                                </button>
                                {% endif %}

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>


<!-- Modal Editar -->
<div class="modal fade" id="editar" role="dialog">

</div>

<!-- Modal Eliminar -->
<div class="modal fade" id="eliminar" role="dialog">

</div>

<!-- Large modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="detalle" aria-hidden="true">

</div>


{% endblock content_main%}


{% block content_extra_js %}


{% endblock content_extra_js %}