mies/mies/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import views as usuario_views
from red import views as red_views
from empleado import views as empleado_views
from ubicacion import views as ubicacion_views
from practica import views as practica_views
from actividad import views as actividad_views
from capacitacion import views as capacitacion_views
from inventario import views as inventario_views
from custodia import views as custodia_views
from configuracion import views as configuracion_views
from django.conf import settings
from django.conf.urls.static import static
#400
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [

    path('admin/', admin.site.urls),
    #MENU PARA LOS USUARIOS
    path('', usuario_views.dashboard_view.as_view(), name="dashboard") ,
   
    #MODULO OTROS
    # ACCESO A REDES  
    path('AccesoRed', red_views.AccesoRedListView.as_view(), name="accesoRed_listar") ,
    path('AccesoRed/Crear', red_views.AccesoRedCreateView.as_view(), name="accesoRed_crear") ,
    path('AccesoRed/Excel', red_views.AccesoRedExcelListView.as_view(), name="accesoRedExcel_crear") ,
    path('AccesoRed/Editar/<int:pk>', red_views.AccesoRedUpdateView.as_view(), name="accesoRed_editar") ,
    path('AccesoRed/Eliminar/<int:pk>', red_views.AccesoRedDeleteView.as_view(), name="accesoRed_eliminar") ,
    path('AccesoRed/Detalle/<int:pk>', red_views.AccesoRedDetailView.as_view(), name="accesoRed_detalle") ,
    #MODULO DE EMPLEADO
    #-- empleado
    path('Empleado', empleado_views.EmpleadoListView.as_view(), name="empleado_listar") ,
    path('Empleado/Crear', empleado_views.EmpleadoCreateView.as_view(), name="empleado_crear") ,
    path('Empleado/Excel', empleado_views.EmpleadoExcelListView.as_view(), name="empleadoExcel_crear") ,
    path('Empleado/Editar/<int:pk>', empleado_views.EmpleadoUpdateView.as_view(), name="empleado_editar") ,
    path('Empleado/Eliminar/<int:pk>', empleado_views.EmpleadoDeleteView.as_view(), name="empleado_eliminar") ,
    path('Empleado/Detalle/<int:pk>', empleado_views.EmpleadoDetailView.as_view(), name="empleado_detalle") ,
    #--area
    path('Area', empleado_views.AreaListView.as_view(), name="area_listar") ,
    path('Area/Crear', empleado_views.AreaCreateView.as_view(), name="area_crear") ,
    path('Area/Editar/<int:pk>', empleado_views.AreaUpdateView.as_view(), name="area_editar") ,
    path('Area/Eliminar/<int:pk>', empleado_views.AreaDeleteView.as_view(), name="area_eliminar") ,
    path('Area/Detalle/<int:pk>', empleado_views.AreaDetailView.as_view(), name="area_detalle") ,
    #--cargo
    path('Cargo', empleado_views.CargoListView.as_view(), name="cargo_listar") ,
    path('Cargo/Crear', empleado_views.CargoCreateView.as_view(), name="cargo_crear") ,
    path('Cargo/Editar/<int:pk>', empleado_views.CargoUpdateView.as_view(), name="cargo_editar") ,
    path('Cargo/Eliminar/<int:pk>', empleado_views.CargoDeleteView.as_view(), name="cargo_eliminar") ,
    path('Cargo/Detalle/<int:pk>', empleado_views.CargoDetailView.as_view(), name="cargo_detalle") ,
    #--unidad de atencion
    path('UnidadAtencion', empleado_views.UnidadListView.as_view(), name="unidad_listar") ,
    path('UnidadAtencion/Crear', empleado_views.UnidadCreateView.as_view(), name="unidad_crear") ,
    path('UnidadAtencion/Editar/<int:pk>', empleado_views.UnidadUpdateView.as_view(), name="unidad_editar") ,
    path('UnidadAtencion/Eliminar/<int:pk>', empleado_views.UnidadDeleteView.as_view(), name="unidad_eliminar") ,
    path('UnidadAtencion/Detalle/<int:pk>', empleado_views.UnidadDetailView.as_view(), name="unidad_detalle") ,
    #MODULO UBICACION DISTRITAL
    #--zona
    path('Zona', ubicacion_views.ZonaListView.as_view(), name="zona_listar") ,
    path('Zona/Crear', ubicacion_views.ZonaCreateView.as_view(), name="zona_crear") ,
    path('Zona/Editar/<int:pk>', ubicacion_views.ZonaUpdateView.as_view(), name="zona_editar") ,
    path('Zona/Eliminar/<int:pk>', ubicacion_views.ZonaDeleteView.as_view(), name="zona_eliminar") ,
    path('Zona/Detalle/<int:pk>', ubicacion_views.ZonaDetailView.as_view(), name="zona_detalle") ,
    #--provincia
    path('Provincia', ubicacion_views.ProvinciaListView.as_view(), name="provincia_listar") ,
    path('Provincia/Crear', ubicacion_views.ProvinciaCreateView.as_view(), name="provincia_crear") ,
    path('Provincia/Editar/<int:pk>', ubicacion_views.ProvinciaUpdateView.as_view(), name="provincia_editar") ,
    path('Provincia/Eliminar/<int:pk>', ubicacion_views.ProvinciaDeleteView.as_view(), name="provincia_eliminar") ,
    path('Provincia/Detalle/<int:pk>', ubicacion_views.ProvinciaDetailView.as_view(), name="provincia_detalle") ,
    #--distrito
    path('Distrito', ubicacion_views.DistritoListView.as_view(), name="distrito_listar") ,
    path('Distrito/Crear', ubicacion_views.DistritoCreateView.as_view(), name="distrito_crear") ,
    path('Distrito/Editar/<int:pk>', ubicacion_views.DistritoUpdateView.as_view(), name="distrito_editar") ,
    path('Distrito/Eliminar/<int:pk>', ubicacion_views.DistritoDeleteView.as_view(), name="distrito_eliminar") ,
    path('Distrito/Detalle/<int:pk>', ubicacion_views.DistritoDetailView.as_view(), name="distrito_detalle") ,
    #MODULO PRACTICAS PROFESIONALIZANTES
    #--Pasante
    path('Pasante', practica_views.PasanteListView.as_view(), name="pasante_listar") ,
    path('Pasante/Crear', practica_views.PasanteCreateView.as_view(), name="pasante_crear") ,
    path('Pasante/Excel', practica_views.PasanteExcelListView.as_view(), name="pasanteExcel_crear") ,
    path('Pasante/Editar/<int:pk>', practica_views.PasanteUpdateView.as_view(), name="pasante_editar") ,
    path('Pasante/Eliminar/<int:pk>', practica_views.PasanteDeleteView.as_view(), name="pasante_eliminar") ,
    path('Pasante/Detalle/<int:pk>', practica_views.PasanteDetailView.as_view(), name="pasante_detalle") ,
    #--Carrera
    path('Carrera', practica_views.CarreraListView.as_view(), name="carrera_listar") ,
    path('Carrera/Crear', practica_views.CarreraCreateView.as_view(), name="carrera_crear") ,
    path('Carrera/Editar/<int:pk>', practica_views.CarreraUpdateView.as_view(), name="carrera_editar") ,
    path('Carrera/Eliminar/<int:pk>', practica_views.CarreraDeleteView.as_view(), name="carrera_eliminar") ,
    path('Carrera/Detalle/<int:pk>', practica_views.CarreraDetailView.as_view(), name="carrera_detalle") ,
    #--Universidad
    path('Universidad', practica_views.UniversidadListView.as_view(), name="universidad_listar") ,
    path('Universidad/Crear', practica_views.UniversidadCreateView.as_view(), name="universidad_crear") ,
    path('Universidad/Editar/<int:pk>', practica_views.UniversidadUpdateView.as_view(), name="universidad_editar") ,
    path('Universidad/Eliminar/<int:pk>', practica_views.UniversidadDeleteView.as_view(), name="universidad_eliminar") ,
    path('Universidad/Detalle/<int:pk>', practica_views.UniversidadDetailView.as_view(), name="universidad_detalle") ,
    

    #MODULO ACTIVIDAD
    #--Actividad
    path('Actividad', actividad_views.ActividadListView.as_view(), name="actividad_listar"),
    path('Actividad/Crear',actividad_views.ActividadCreateView.as_view(),name ="actividad_crear"),
    path('Actividad/pdf/<int:pk>', actividad_views.ActividadReportePdfDetailView.as_view(), name="actividad_reporte_pdf") ,
    path('Actividad/Editar/<int:pk>',actividad_views.ActividadUpdateView.as_view(),name ="actividad_editar"),
    path('Actividad/Eliminar/<int:pk>',actividad_views.ActividadDeleteView.as_view(),name ="actividad_eliminar"),
    path('Actividad/Detalle/<int:pk>',actividad_views.ActividadDetailView.as_view(),name ="actividad_detalle"),
   
    #--Asunto
    path('Asunto', actividad_views.AsuntoListView.as_view(), name="asunto_listar"),
    path('Asunto/Crear',actividad_views.AsuntoCreateView.as_view(),name ="asunto_crear"),
    path('Asunto/Editar/<int:pk>',actividad_views.AsuntoUpdateView.as_view(),name ="asunto_editar"),
    path('Asunto/Eliminar/<int:pk>',actividad_views.AsuntoDeleteView.as_view(),name ="asunto_eliminar"),
    path('Asunto/Detalle/<int:pk>',actividad_views.AsuntoDetailView.as_view(),name ="asunto_detalle"),

     #--Capacitacion
    path('Capacitacion', capacitacion_views.CapacitacionListView.as_view(), name="capacitacion_listar") ,
    path('Capacitacion/Crear', capacitacion_views.CapacitacionCreateView.as_view(), name="capacitacion_crear") ,
    path('Capacitacion/Editar/<int:pk>', capacitacion_views.CapacitacionUpdateView.as_view(), name="capacitacion_editar") ,
    path('Capacitacion/Eliminar/<int:pk>', capacitacion_views.CapacitacionDeleteView.as_view(), name="capacitacion_eliminar") ,
    path('Capacitacion/Detalle/<int:pk>', capacitacion_views.CapacitacionDetailView.as_view(), name="capacitacion_detalle") ,
    path('Capacitacion/pdf/<int:pk>', capacitacion_views.CapacitacionReportePdfDetailView.as_view(), name="capacitacion_reporte_pdf") ,


    #Modulo Inventario 
    #--Marca
    path('Marca', inventario_views.MarcaListView.as_view(), name="marca_listar"),
    path('Marca/Crear',inventario_views.MarcaCreateView.as_view(),name ="marca_crear"),
    path('Marca/Editar/<int:pk>',inventario_views.MarcaUpdateView.as_view(),name ="marca_editar"),
    path('Marca/Eliminar/<int:pk>',inventario_views.MarcaDeleteView.as_view(),name ="marca_eliminar"),
    path('Marca/Detalle/<int:pk>',inventario_views.MarcaDetailView.as_view(),name ="marca_detalle"),
    #--Modelo
    path('Modelo', inventario_views.ModeloListView.as_view(), name="modelo_listar"),
    path('Modelo/Crear',inventario_views.ModeloCreateView.as_view(),name ="modelo_crear"),
    path('Modelo/Editar/<int:pk>',inventario_views.ModeloUpdateView.as_view(),name ="modelo_editar"),
    path('Modelo/Eliminar/<int:pk>',inventario_views.ModeloDeleteView.as_view(),name ="modelo_eliminar"),
    path('Modelo/Detalle/<int:pk>',inventario_views.ModeloDetailView.as_view(),name ="modelo_detalle"),

mies/practica/models.py
from django.db import models
from empleado.models import Empleado

# Creacion de modelos del modulo Practicas Profesionalizantes
#modelo UNIVERSIDAD
class Universidad(models.Model):
    """Model definition for Universidad."""

    descripcion = models.CharField('Universidad', max_length=50,unique = True)

    class Meta:
        """Meta definition for Universidad."""

        verbose_name = 'Universidad'
        verbose_name_plural = 'Universidades'

    def __str__(self):
        """Unicode representation of Universidad."""
        return self.descripcion

    def save(self,*args, **kwargs):
        """Save method for Universidad."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Universidad, self).save(*args, **kwargs)

#modelo CARRERA
class Carrera(models.Model):
    """Model definition for Carrera."""

    universidad = models.ForeignKey(Universidad, on_delete=models.PROTECT )
    descripcion = models.CharField('Carrera', max_length=50 )

    class Meta:
        """Meta definition for Carrera."""

        verbose_name = 'Carrera'
        verbose_name_plural = 'Carreras'

    def __str__(self):
        """Unicode representation of Carrera."""
        return self.descripcion

    def save(self,*args, **kwargs):
        """Save method for Carrera."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Carrera, self).save(*args, **kwargs)

#modelo PASANTE
class Pasante(models.Model):
    """Model definition for Pasante."""

    nombres = models.CharField('Nombres', max_length=50)
    apellidos = models.CharField('Apellidos', max_length=50)
    cedula = models.CharField('Cédula', max_length=10,unique= True,null= True, blank=True)
    telefono = models.CharField('Teléfono Móvil', max_length=10,unique= True,null= True, blank=True)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT)
    tutor_profesional = models.ForeignKey(Empleado, on_delete=models.PROTECT)
    fecha_inicio = models.DateField('Fecha Inicio', auto_now=False, auto_now_add=False)
    fecha_fin = models.DateField('Fecha Fin', auto_now=False, auto_now_add=False, null= True, blank=True)
    horas_diarias = models.IntegerField('Horas Diarias', default =1)
    lista_estado= [
    ('1', 'EN FUNCIONES'),
    ('2', 'SOLICITADO'),
    ('3', 'FINALIZADO'),]
    estado = models.CharField('Estado',max_length=1, choices=lista_estado, default='1')
  
    class Meta:
        """Meta definition for Pasante."""

        verbose_name = 'Pasante'
        verbose_name_plural = 'Pasantes'

    def __str__(self):
        """Unicode representation of Pasante."""
        return self.apellidos

    def save(self,*args, **kwargs):
        """Save method for Pasante."""
        self.nombres = self.nombres and (self.nombres).upper()
        self.apellidos = self.apellidos and (self.apellidos).upper()
        return super(Pasante, self).save(*args, **kwargs)

mies/practica/forms.py
from django import forms
from .models import Pasante, Carrera, Universidad
from django.utils.encoding import force_text
from django.utils.html import format_html
from django.utils.safestring import mark_safe




class PasanteForm(forms.ModelForm):       
    """Form definition for Pasant."""
    #extra field -no estan directamente en el modelo
    universidad = forms.ModelChoiceField(
         queryset= Universidad.objects.all(), 
         widget= forms.Select( attrs={
                    'class': 'form-control select'
                }
            ))




    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tutor_profesional'].empty_label = "------N/A--------"
        self.fields['carrera'].empty_label = "------N/A--------"
        self.fields['universidad'].empty_label = "------N/A--------"
       
      
    class Meta:
        """Meta definition for Pasanteform."""

        model= Pasante
        fields = (
            'nombres',
            'apellidos',
            'cedula',
            'telefono',
            'carrera',
            'tutor_profesional',
            'fecha_inicio',
            'fecha_fin',
            'horas_diarias',
            'estado',
            
            )
      

        widgets = {
            'nombres': forms.TextInput(
                attrs={
                    'class': 'form-control solo-letra'
                }
            ),
            'apellidos': forms.TextInput(
                attrs={
                    'class': 'form-control solo-letra'
                }
            ),
            'cedula': forms.TextInput(
                attrs={
                    'class': 'form-control solo-numero'
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control solo-numero'
                }
            ),
          
            'carrera' : forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'tutor_profesional' : forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'fecha_inicio': forms.TextInput(
                attrs={
                    'type':'date',
                    'class': 'form-control'
                }
            ),
            'fecha_fin': forms.TextInput(
                attrs={
                    'type':'date',
                    'class': 'form-control'
                }
            ),
            'horas_diarias': forms.TextInput(
                attrs={
                    'type':'number',
                    'class': 'form-control solo-numero',
                    'min':'1'
                }
            ),
            'estado': forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),                   
            }

class CarreraForm(forms.ModelForm):
    def clean_descripcion(self):
        data = self.cleaned_data["descripcion"].upper()
        
        return data
    
    class Meta:

        model = Carrera

        fields = (
            'descripcion',
            'universidad',)
        
        widgets = {
            'universidad' : forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'descripcion' : forms.TextInput(
                attrs={
                    'class': 'form-control solo-letra',
                    'autofocus':'autofocus'
                }
            ),
        }

class UniversidadForm(forms.ModelForm):

    def clean_descripcion(self):
        data = self.cleaned_data["descripcion"].upper()
        return data

    class Meta:

        model = Universidad

        fields = (
            'descripcion',)
        
        widgets = {
            'descripcion' : forms.TextInput(
                attrs={
                    'class': 'form-control solo-letra',
                    'autofocus':'autofocus'
                }
            ),
        }

mies/templates/practica/carrera_detalle.html
<div class="modal-dialog modal-lg ">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Detalle Registro</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <table class="table table-bordered table-responsive-sm">
                <tbody>
                    <tr>
                        <th>Universidad:</th>
                        <td> {{object.universidad}} </td>
                    </tr>
                    <tr>
                        <th>Carrera:</th>
                        <td colspan="4">{{object.descripcion}}</td>
                    </tr>
                </tbody>
            </table>


        </div>

        
    </div>

</div>

mies/templates/practica/carrera_listado.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %}CARRERA{% endblock title %}


{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pasante_listar' %}">Pasantes</a></li>
        <li class="breadcrumb-item active" aria-current="page">Carrera</li>
    </ol>
</nav>
<div class="container-fluid">
    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row ">
                <div class="col">
                    <h6 class="m-0 font-weight-bold text-primary">Listado de Carreras</h6>
                </div>
                <div class="col ">
                    {% if perms.practica.add_carrera %}
                        <div class="float-right">
                            
                            <a class="btn btn-secondary btn-sm" href="{% url 'carrera_crear'%}" role="button"> Nuevo</a>
                    
                        </div>
                    {% endif %}
                   
                </div>
            </div>

        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><b>CARRERA</b></th>
                            <th><b>UNIVERSIDAD</b></th>
                            <th><b>ACCIONES</b></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for carrera in object_list %}
                        <tr>
                            <td>{{ carrera.descripcion }}</td>
                            <td>{{ carrera.universidad }}</td>


                            <td>
                                <a data-toggle="popover" title="Ver" class="btn btn-light btn-sm "
                                    onclick="abrirModalDetalle('{% url 'carrera_detalle' carrera.id%}')"> <i
                                        data-toggle="popover" title="Ver" class="fa fa-eye"></i>
                                </a>

                                {% if perms.practica.change_carrera %}
                                <button id="modalEditarCarrera" class="btn btn-light btn-sm"
                                onclick="abrirModalEditar('{% url 'carrera_editar' carrera.id%}')"> <i
                                    class="fa fa-edit"></i>
                            </button>
                                {% endif %}


                                {% if perms.practica.delete_carrera%}
                                <a data-toggle="popover" title="Eliminar" class="btn btn-light btn-sm"
                                    onclick="abrirModalEliminar('{% url 'carrera_eliminar' carrera.id%}')"><i
                                        data-toggle="popover" title="Eliminar" class="fa fa-trash"></i>
                                </a>
                                {% endif %}

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</div>


<!-- Modal Editar -->
<div class="modal fade" id="editar" role="dialog">

</div>

<!-- Modal Eliminar -->
<div class="modal fade" id="eliminar" role="dialog">

</div>

<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="detalle" aria-hidden="true">

</div>


{% endblock content_main%}

{% block content_extra_js %}

{% endblock content_extra_js %}

mies/templates/practica/pasante_crear.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %}NUEVO PASANTE{% endblock %}


{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pasante_listar' %}">Pasantes</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
    </ol>
</nav>

<div class="container">

    {% if form.errors %}

    <div class="alert alert-danger" role="alert">
        <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
        <ul>
            {% for field in form %}
            {% for error in field.errors %}
            <li>
                {{error}}
            </li>
            {% endfor %}
            {% endfor %}
        </ul>

    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <div class="form-group col-md-4">
                <label for="id_nomnbres">{{form.nombres.label}}*</label>
                {{form.nombres}}
            </div>
            <div class="form-group col-md-4">
               <label for="id_apellidos"> {{form.apellidos.label}}*</label>
                {{form.apellidos}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_cedula">{{form.cedula.label}}*</label>
                {{form.cedula}}
            </div>
        </div>
        <div class="row">
           
            <div class="form-group col-md-4">
                <label for="id_telefono">{{form.telefono.label}}</label>
                {{form.telefono}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_tutor_profesional">{{form.tutor_profesional.label}}*</label>
                {{form.tutor_profesional}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_horas_diariras">{{form.horas_diarias.label}}*</label>
                {{form.horas_diarias}}
            </div>
        </div>
       
        <div class="row">
            <div class="form-group col-md-6">
                
                <label for="id_universidad">Universidad</label>
                <label for="id_universidad">{{form.universidad.label}}</label>
                {{form.universidad}}
            </div>
           
            <div class="form-group col-md-6">
                <label for="id_carrera">Carrera*</label>
                <select name="carrera" id="id_carrera" class="form-control select">
                    <option value="0">---------</option>
                    {% for item in carreras %}
                    <option value="{{item.id}}" class="{{item.universidad.id}}">{{item.descripcion}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-4">
                <label for="id_fecha_inicio">{{form.fecha_inicio.label}}*</label>
                {{form.fecha_inicio}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_fecha_fin">{{form.fecha_fin.label}}*</label>
                {{form.fecha_fin}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_estado">{{form.estado.label}}*</label>
                {{form.estado}}
            </div>
            

        </div>

        <fieldset class="modal-footer">
            <a type="button" class="btn btn-secondary" href="{% url 'pasante_listar' %}">Cancelar</a>
            <button type="submit" class="btn  btn-primary">Guardar Registro</button>
        </fieldset>
    </form>
</div>

{% endblock %}

{% block content_extra_js %}

<script>
    $(function () {

        $("#id_carrera").chained("#id_universidad");
    });

</script>


{% endblock content_extra_js %}

mies/templates/practica/pasante_editar.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar Registro</h5>
           
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          
  
        </div>
        
        <form action="{% url 'pasante_editar' object.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="modal-body">
              
        <div class="row">
            <div class="form-group col-md-4">
                <label for="id_nomnbres">{{form.nombres.label}}*</label>
                {{form.nombres}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_apellidos"> {{form.apellidos.label}}*</label>
                {{form.apellidos}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_cedula">{{form.cedula.label}}*</label>
                {{form.cedula}}
            </div>
        </div>
        <div class="row">
           
            <div class="form-group col-md-4">
                <label for="id_telefono">{{form.telefono.label}}</label>
                {{form.telefono}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_tutor_profesional">{{form.tutor_profesional.label}}*</label>
                {{form.tutor_profesional}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_horas_diariras">{{form.horas_diarias.label}}*</label>
                {{form.horas_diarias}}
            </div>
        </div>
       
        <div class="row">

            <div class="form-group col-md-6">
                <label for="id_carrera">Universidad</label>
                <select name="universidad" id="id_universidad" class="form-control select">
                    <option value="0">---------</option>
                    {% for item in universidades %}
                    <option value="{{item.id}}" 
                    {% if update_universidad == item.id %}
                       selected
                    {% endif %}
                    >{{item.descripcion}}</option>
                    {% endfor %}
                </select>
            </div>
           
           

            <div class="form-group col-md-6">
                <label for="id_carrera">Carrera*</label>
                <select name="carrera" id="id_carrera" class="form-control select">
                    <option value="0">---------</option>
                    {% for item in carreras %}
                    <option value="{{item.id}}" class="{{item.universidad.id}}"
                    {% if update_carrera == item.id %}
                       selected
                    {% endif %}
                    
                    >{{item.descripcion}}</option>
                    
                        
                    {% endfor %}
                </select>
            </div>

        </div>

        <div class="row">
            <div class="form-group col-md-4">
                <label for="id_fecha_inicio">{{form.fecha_inicio.label}}*</label>
                {{form.fecha_inicio}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_fecha_fin">{{form.fecha_fin.label}}*</label>
                {{form.fecha_fin}}
            </div>
            <div class="form-group col-md-4">
                <label for="id_estado">{{form.estado.label}}*</label>
                {{form.estado}}
            </div>
            

        </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
        </form>
    </div>
</div>

{% block content_extra_js %}


<script>
    $(function () {

     
        $("#id_carrera").chained("#id_universidad");
        
    });

</script>


{% endblock content_extra_js %}