mies/mies/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import views as usuario_views
from red import views as red_views
from empleado import views as empleado_views
from ubicacion import views as ubicacion_views
from practica import views as practica_views
from actividad import views as actividad_views
from capacitacion import views as capacitacion_views
from inventario import views as inventario_views
from custodia import views as custodia_views
from configuracion import views as configuracion_views
from django.conf import settings
from django.conf.urls.static import static
#400
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [

    path('admin/', admin.site.urls),
    #MENU PARA LOS USUARIOS
    path('', usuario_views.dashboard_view.as_view(), name="dashboard") ,
   
    #MODULO OTROS
    # ACCESO A REDES  
    path('AccesoRed', red_views.AccesoRedListView.as_view(), name="accesoRed_listar") ,
    path('AccesoRed/Crear', red_views.AccesoRedCreateView.as_view(), name="accesoRed_crear") ,
    path('AccesoRed/Excel', red_views.AccesoRedExcelListView.as_view(), name="accesoRedExcel_crear") ,
    path('AccesoRed/Editar/<int:pk>', red_views.AccesoRedUpdateView.as_view(), name="accesoRed_editar") ,
    path('AccesoRed/Eliminar/<int:pk>', red_views.AccesoRedDeleteView.as_view(), name="accesoRed_eliminar") ,
    path('AccesoRed/Detalle/<int:pk>', red_views.AccesoRedDetailView.as_view(), name="accesoRed_detalle") ,
    #MODULO DE EMPLEADO
    #-- empleado
    path('Empleado', empleado_views.EmpleadoListView.as_view(), name="empleado_listar") ,
    path('Empleado/Crear', empleado_views.EmpleadoCreateView.as_view(), name="empleado_crear") ,
    path('Empleado/Excel', empleado_views.EmpleadoExcelListView.as_view(), name="empleadoExcel_crear") ,
    path('Empleado/Editar/<int:pk>', empleado_views.EmpleadoUpdateView.as_view(), name="empleado_editar") ,
    path('Empleado/Eliminar/<int:pk>', empleado_views.EmpleadoDeleteView.as_view(), name="empleado_eliminar") ,
    path('Empleado/Detalle/<int:pk>', empleado_views.EmpleadoDetailView.as_view(), name="empleado_detalle") ,
    #--area
    path('Area', empleado_views.AreaListView.as_view(), name="area_listar") ,
    path('Area/Crear', empleado_views.AreaCreateView.as_view(), name="area_crear") ,
    path('Area/Editar/<int:pk>', empleado_views.AreaUpdateView.as_view(), name="area_editar") ,
    path('Area/Eliminar/<int:pk>', empleado_views.AreaDeleteView.as_view(), name="area_eliminar") ,
    path('Area/Detalle/<int:pk>', empleado_views.AreaDetailView.as_view(), name="area_detalle") ,
    #--cargo
    path('Cargo', empleado_views.CargoListView.as_view(), name="cargo_listar") ,
    path('Cargo/Crear', empleado_views.CargoCreateView.as_view(), name="cargo_crear") ,
    path('Cargo/Editar/<int:pk>', empleado_views.CargoUpdateView.as_view(), name="cargo_editar") ,
    path('Cargo/Eliminar/<int:pk>', empleado_views.CargoDeleteView.as_view(), name="cargo_eliminar") ,
    path('Cargo/Detalle/<int:pk>', empleado_views.CargoDetailView.as_view(), name="cargo_detalle") ,
    #--unidad de atencion
    path('UnidadAtencion', empleado_views.UnidadListView.as_view(), name="unidad_listar") ,
    path('UnidadAtencion/Crear', empleado_views.UnidadCreateView.as_view(), name="unidad_crear") ,
    path('UnidadAtencion/Editar/<int:pk>', empleado_views.UnidadUpdateView.as_view(), name="unidad_editar") ,
    path('UnidadAtencion/Eliminar/<int:pk>', empleado_views.UnidadDeleteView.as_view(), name="unidad_eliminar") ,
    path('UnidadAtencion/Detalle/<int:pk>', empleado_views.UnidadDetailView.as_view(), name="unidad_detalle") ,
    #MODULO UBICACION DISTRITAL
    #--zona
    path('Zona', ubicacion_views.ZonaListView.as_view(), name="zona_listar") ,
    path('Zona/Crear', ubicacion_views.ZonaCreateView.as_view(), name="zona_crear") ,
    path('Zona/Editar/<int:pk>', ubicacion_views.ZonaUpdateView.as_view(), name="zona_editar") ,
    path('Zona/Eliminar/<int:pk>', ubicacion_views.ZonaDeleteView.as_view(), name="zona_eliminar") ,
    path('Zona/Detalle/<int:pk>', ubicacion_views.ZonaDetailView.as_view(), name="zona_detalle") ,
    #--provincia
    path('Provincia', ubicacion_views.ProvinciaListView.as_view(), name="provincia_listar") ,
    path('Provincia/Crear', ubicacion_views.ProvinciaCreateView.as_view(), name="provincia_crear") ,
    path('Provincia/Editar/<int:pk>', ubicacion_views.ProvinciaUpdateView.as_view(), name="provincia_editar") ,
    path('Provincia/Eliminar/<int:pk>', ubicacion_views.ProvinciaDeleteView.as_view(), name="provincia_eliminar") ,
    path('Provincia/Detalle/<int:pk>', ubicacion_views.ProvinciaDetailView.as_view(), name="provincia_detalle") ,
    #--distrito
    path('Distrito', ubicacion_views.DistritoListView.as_view(), name="distrito_listar") ,
    path('Distrito/Crear', ubicacion_views.DistritoCreateView.as_view(), name="distrito_crear") ,
    path('Distrito/Editar/<int:pk>', ubicacion_views.DistritoUpdateView.as_view(), name="distrito_editar") ,
    path('Distrito/Eliminar/<int:pk>', ubicacion_views.DistritoDeleteView.as_view(), name="distrito_eliminar") ,
    path('Distrito/Detalle/<int:pk>', ubicacion_views.DistritoDetailView.as_view(), name="distrito_detalle") ,
    #MODULO PRACTICAS PROFESIONALIZANTES
    #--Pasante
    path('Pasante', practica_views.PasanteListView.as_view(), name="pasante_listar") ,
    path('Pasante/Crear', practica_views.PasanteCreateView.as_view(), name="pasante_crear") ,
    path('Pasante/Excel', practica_views.PasanteExcelListView.as_view(), name="pasanteExcel_crear") ,
    path('Pasante/Editar/<int:pk>', practica_views.PasanteUpdateView.as_view(), name="pasante_editar") ,
    path('Pasante/Eliminar/<int:pk>', practica_views.PasanteDeleteView.as_view(), name="pasante_eliminar") ,
    path('Pasante/Detalle/<int:pk>', practica_views.PasanteDetailView.as_view(), name="pasante_detalle") ,
    #--Carrera
    path('Carrera', practica_views.CarreraListView.as_view(), name="carrera_listar") ,
    path('Carrera/Crear', practica_views.CarreraCreateView.as_view(), name="carrera_crear") ,
    path('Carrera/Editar/<int:pk>', practica_views.CarreraUpdateView.as_view(), name="carrera_editar") ,
    path('Carrera/Eliminar/<int:pk>', practica_views.CarreraDeleteView.as_view(), name="carrera_eliminar") ,
    path('Carrera/Detalle/<int:pk>', practica_views.CarreraDetailView.as_view(), name="carrera_detalle") ,
    #--Universidad
    path('Universidad', practica_views.UniversidadListView.as_view(), name="universidad_listar") ,
    path('Universidad/Crear', practica_views.UniversidadCreateView.as_view(), name="universidad_crear") ,
    path('Universidad/Editar/<int:pk>', practica_views.UniversidadUpdateView.as_view(), name="universidad_editar") ,
    path('Universidad/Eliminar/<int:pk>', practica_views.UniversidadDeleteView.as_view(), name="universidad_eliminar") ,
    path('Universidad/Detalle/<int:pk>', practica_views.UniversidadDetailView.as_view(), name="universidad_detalle") ,
    

    #MODULO ACTIVIDAD
    #--Actividad
    path('Actividad', actividad_views.ActividadListView.as_view(), name="actividad_listar"),
    path('Actividad/Crear',actividad_views.ActividadCreateView.as_view(),name ="actividad_crear"),
    path('Actividad/pdf/<int:pk>', actividad_views.ActividadReportePdfDetailView.as_view(), name="actividad_reporte_pdf") ,
    path('Actividad/Editar/<int:pk>',actividad_views.ActividadUpdateView.as_view(),name ="actividad_editar"),
    path('Actividad/Eliminar/<int:pk>',actividad_views.ActividadDeleteView.as_view(),name ="actividad_eliminar"),
    path('Actividad/Detalle/<int:pk>',actividad_views.ActividadDetailView.as_view(),name ="actividad_detalle"),
   
    #--Asunto
    path('Asunto', actividad_views.AsuntoListView.as_view(), name="asunto_listar"),
    path('Asunto/Crear',actividad_views.AsuntoCreateView.as_view(),name ="asunto_crear"),
    path('Asunto/Editar/<int:pk>',actividad_views.AsuntoUpdateView.as_view(),name ="asunto_editar"),
    path('Asunto/Eliminar/<int:pk>',actividad_views.AsuntoDeleteView.as_view(),name ="asunto_eliminar"),
    path('Asunto/Detalle/<int:pk>',actividad_views.AsuntoDetailView.as_view(),name ="asunto_detalle"),

     #--Capacitacion
    path('Capacitacion', capacitacion_views.CapacitacionListView.as_view(), name="capacitacion_listar") ,
    path('Capacitacion/Crear', capacitacion_views.CapacitacionCreateView.as_view(), name="capacitacion_crear") ,
    path('Capacitacion/Editar/<int:pk>', capacitacion_views.CapacitacionUpdateView.as_view(), name="capacitacion_editar") ,
    path('Capacitacion/Eliminar/<int:pk>', capacitacion_views.CapacitacionDeleteView.as_view(), name="capacitacion_eliminar") ,
    path('Capacitacion/Detalle/<int:pk>', capacitacion_views.CapacitacionDetailView.as_view(), name="capacitacion_detalle") ,
    path('Capacitacion/pdf/<int:pk>', capacitacion_views.CapacitacionReportePdfDetailView.as_view(), name="capacitacion_reporte_pdf") ,


    #Modulo Inventario 
    #--Marca
    path('Marca', inventario_views.MarcaListView.as_view(), name="marca_listar"),
    path('Marca/Crear',inventario_views.MarcaCreateView.as_view(),name ="marca_crear"),
    path('Marca/Editar/<int:pk>',inventario_views.MarcaUpdateView.as_view(),name ="marca_editar"),
    path('Marca/Eliminar/<int:pk>',inventario_views.MarcaDeleteView.as_view(),name ="marca_eliminar"),
    path('Marca/Detalle/<int:pk>',inventario_views.MarcaDetailView.as_view(),name ="marca_detalle"),
    #--Modelo
    path('Modelo', inventario_views.ModeloListView.as_view(), name="modelo_listar"),
    path('Modelo/Crear',inventario_views.ModeloCreateView.as_view(),name ="modelo_crear"),
    path('Modelo/Editar/<int:pk>',inventario_views.ModeloUpdateView.as_view(),name ="modelo_editar"),
    path('Modelo/Eliminar/<int:pk>',inventario_views.ModeloDeleteView.as_view(),name ="modelo_eliminar"),
    path('Modelo/Detalle/<int:pk>',inventario_views.ModeloDetailView.as_view(),name ="modelo_detalle"),

mies/custodia/models.py
from django.db import models
from django.utils import timezone
from empleado.models import Empleado
from inventario.models import Dispositivo
# Create your models here.
class Custodia(models.Model):
    """Model definition for AccesoRed."""

    fecha = models.DateField('Fecha',default=timezone.now)
    custodio = models.ForeignKey(Empleado,verbose_name='Custodio', on_delete=models.PROTECT)
    equipo = models.ForeignKey(Dispositivo, on_delete=models.PROTECT)
    custodioAnterior = models.ForeignKey(Empleado,verbose_name='Custodio Anterior',related_name="custodioAnterior", on_delete=models.PROTECT,  null= True, blank=True)
    estado = models.BooleanField('Estado', default = True)

    class Meta:
        """Meta definition for AccesoRed."""

        verbose_name = 'Asignar Custodio'
        verbose_name_plural = 'Asignar Custodios'

    def __str__(self):
        """Unicode representation of AccesoRed."""
        return ("{} {}").format(self.custodio.apellidos, self.custodio.nombres)

    def save(self, *args, **kwargs):
        
        try:
            #cambio el estado a no vigente. al equipo que se este creando 
            equipo =  Custodia.objects.filter(equipo=self.equipo.id, estado=1).update(estado=0)
        except:
            pass
        return super(Custodia, self).save(*args, **kwargs)
 

mies/custodia/forms.py
from django import forms
from .models import Custodia
from empleado.models import Empleado
from inventario.models import Dispositivo
class CustodiaForm(forms.ModelForm):
    """Form definition for AccesoRed."""
    def __init__(self, *args, **kwargs):
        super(CustodiaForm, self).__init__(*args, **kwargs)
        # Filtro al responsable de acuerdo a su cargo id =1; -> tics
        self.fields['custodio'].queryset = Empleado.objects.filter(estado=1)
        self.fields['categoria'].empty_label = "------N/A--------"
        #filtro que muestre solo los empleados con condicion bueno o regular excluye el id 3 -> de dañado
        #self.fields['equipo'].queryset = Dispositivo.objects.exclude( estado=3)
       
    categoria = forms.ChoiceField(label=u"Categoria", choices=[('1', 'COMPUTADORAS'),('2', 'IMPRESORAS'), ('3', 'OTROS DISPOSITIVOS'),], required=False, widget=forms.Select(attrs={'class': 'form-control select'}))
        
    class Meta:
        """Meta definition for AccesoRedform."""
        model = Custodia
        #extra field -no estan directamente en el modelo
        
        

        fields = (
            'fecha',
            'custodio',
            'custodioAnterior',
            'equipo',
            'estado',)
        
        widgets = {
            'fecha': forms.DateInput(format=('%Y-%m-%d'),
                attrs={
                    'type':'date',
                    'class': 'form-control'  
                    }
            ),
            'custodio': forms.Select(
                attrs={
                    
                    'class': 'form-control select'
                }
            ),
            'custodioAnterior': forms.Select(
                attrs={
                    
                    'class': 'form-control ',
                    
                    
                }
            ),
         
            'equipo': forms.Select(
                attrs={
                   
                    'class': 'form-control select'
                }
            ),
      
            'estado': forms.CheckboxInput(
                attrs={
                   
                    'class': 'form-group ',
                  
                }
            ),
        }

mies/templates/custodia/custodiaReasignar.html
{% extends 'base_generic.html' %}
{% block title %}NUEVA ASIGNACIÓN{% endblock %}
{% load static %}

{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'custodia_listar' %}">Custodia</a></li>
        <li class="breadcrumb-item active" aria-current="page">Reasignar Custodia</li>
    </ol>
</nav>
<div class="container">

    {% if form.errors %}

    <div class="alert alert-danger" role="alert">
        <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
        <ul>
            {% for field in form %}
            {% for error in field.errors %}
            <li>
                {{error}}
            </li>
            {% endfor %}
            {% endfor %}
        </ul>

    </div>
    {% endif %}


    <form method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_fecha">{{form.fecha.label}}*</label>
                    {{form.fecha}}
                </div>

            </div>
            <div class="col">
                <div class="form-group ">
                    <label for="id_custodio">{{form.custodio.label}}*</label>
                    {{form.custodio}}
                </div>

            </div>

        </div>
        <div class="row">


            <div class="form-group col-md-6">
                
                    <div class="form-group ">
                        <label for="id_categoria">{{form.categoria.label}}</label>
                        {{form.categoria }}
                    </div>

             
                <label for="id_equipo">Equipo*</label>
                <select name="equipo" id="id_equipo" class="form-control select">
                    <option value="0">---------</option>
                    {% for item in equipos %}
                    <option value="{{item.id}}" class="{{item.categoria}}">

                        {% if item.categoria == '1' %}
                        [{{item.tipoEquipo}}]---[{{item.nombreEquipo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                        {% endif %}
                        {% if item.categoria == '2' %}
                        [{{item.tipoImpresora}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.tecnologia}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                        {% endif %}
                        {% if item.categoria == '3' %}
                        [{{item.tipoDispositivo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                        {% endif %}

                    </option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group col-md-6">
                <label for="id_custodioAnterior">Custodio Anterior*</label>
                <select name="custodioAnterior" id="id_custodioAnterior" class="form-control " readonly>

                    {% for item in custodioAnterior %}
                    <option value="{{item.custodio.id}}" class="{{item.equipo.id}}">{{item.custodio}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <div class="form-check">
                    <label for="id_estado">{{form.estado.label}}</label>
                    {{form.estado}}
                </div>
            </div>
        </div>

        <fieldset class="modal-footer">
            <a type="button" class="btn btn-secondary" href="{% url 'custodia_listar' %}">Cancelar</a>
            <button type="submit" class="btn  btn-primary">Guardar Registro</button>
        </fieldset>
    </form>
</div>

{% endblock %}

{% block content_extra_js %}

<script>
    $(function () {

        $("#id_equipo").chained("#id_categoria");
        $("#id_custodioAnterior").chained("#id_equipo");
    });

</script>

{% endblock content_extra_js %}

mies/templates/custodia/custodia_crear.html
{% extends 'base_generic.html' %}
{% block title %}NUEVA ASIGNACIÓN{% endblock %}
{% load static %}

{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'custodia_listar' %}">Custodia</a></li>
        <li class="breadcrumb-item active" aria-current="page">Asignar Custodia</li>
    </ol>
</nav>
<div class="container">

    {% if form.errors %}

    <div class="alert alert-danger" role="alert">
        <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
        <ul>
            {% for field in form %}
            {% for error in field.errors %}
            <li>
                {{error}}
            </li>
            {% endfor %}
            {% endfor %}
        </ul>

    </div>
    {% endif %}


    <form method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="id_fecha">{{form.fecha.label}}*</label>
                    {{form.fecha}}
                </div>
                
            </div>
            <div class="col">
                <div class="form-group ">
                    <label for="id_custodio">{{form.custodio.label}}*</label>
                    {{form.custodio}}
                </div>
        
                
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group ">
                    <label for="id_categoria">{{form.categoria.label}}*</label>
                    {{form.categoria }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group ">
                    <label for="id_equipo">Equipo*</label>
                    <select name="equipo" id="id_equipo" class="form-control select">
                        <option value="0">---------</option>
                        {% for item in equipos %}
                        <option value="{{item.id}}" class="{{item.categoria}}">
        
                            {% if item.categoria == '1' %}
                            [{{item.tipoEquipo}}]---[{{item.nombreEquipo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                            {% endif %}
                            {% if item.categoria == '2' %}
                            [{{item.tipoImpresora}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.tecnologia}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                            {% endif %}
                            {% if item.categoria == '3' %}
                            [{{item.tipoDispositivo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                            {% endif %}
        
                        </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
       
        <div class="form-row">
            <div class="form-group">
                <div class="form-check">
                    <label for="id_estado">{{form.estado.label}}</label>
                    {{form.estado}}
                </div>
            </div>
        </div>

        <fieldset class="modal-footer">
            <a type="button" class="btn btn-secondary" href="{% url 'custodia_listar' %}">Cancelar</a>
            <button type="submit" class="btn  btn-primary">Guardar Registro</button>
        </fieldset>
    </form>
</div>

{% endblock %}

{% block content_extra_js %}

<script>
    $(function () {

        $("#id_equipo").chained("#id_categoria");
    });

</script>

{% endblock content_extra_js %}

mies/templates/custodia/custodia_editar.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar Registro</h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>


        </div>

        <form action="{% url 'custodia_editar' object.id %}" method="post">
            {% csrf_token %}

            <div class="modal-body">

                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="id_fecha">{{form.fecha.label}}*</label>
                            {{form.fecha}}
                        </div>
                        <div class="form-group ">
                            <label for="id_categoria">Categoria*</label>
                            <select name="categoria" id="id_categoria" class="form-control select">
                                <option value="0">---------</option>
                                <option value="1" 
                                {% if update_categoria == "1" %}
                                    selected
                                {% endif %}
                                    >COMPUTADORAS</option>
                                <option value="2"
                                {% if update_categoria == "2" %}
                                    selected
                                {% endif %}
                                >IMPRESORAS</option>
                                <option value="3"
                                {% if update_categoria == "3" %}
                                    selected
                                {% endif %}
                                >OTROS DISPOSITIVOS</option>
                            </select>
                        </div>
                       
                    </div>
                    <div class="col">
                        <div class="form-group ">
                            <label for="id_custodio">{{form.custodio.label}}*</label>
                            {{form.custodio}}
                        </div>
                      

                        <div class="form-group ">
                            <label for="id_equipo">Equipo*</label>
                            <select name="equipo" id="id_equipo" class="form-control select">
                                <option value="0">---------</option>
                                {% for item in update_equipo %}
                                 <option value="{{item.id}}" class="{{item.categoria}}" selected >

                                    {% if item.categoria == '1' %}
                                    [{{item.tipoEquipo}}]---[{{item.nombreEquipo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                                    {% endif %}
                                    {% if item.categoria == '2' %}
                                    [{{item.tipoImpresora}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.tecnologia}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                                    {% endif %}
                                    {% if item.categoria == '3' %}
                                    [{{item.tipoDispositivo}}]---[{{item.marca}}]---[{{item.modelo}}]---[{{item.codigoMies}}]---[{{item.serie}}]---[{{item.direccionIp}}]---[{{item.direccionMac}}]
                                    {% endif %}
                

                                </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="id_custodioAnterior">Custodio Anterior*</label>
                            <select name="custodioAnterior" id="id_custodioAnterior" class="form-control " readonly>
            
                                {% for item in custodioAnterior %}
                                <option value="{{item.custodioAnterior.id}}">{{item.custodioAnterior}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <div class="form-check">
                            <label for="id_estado">{{form.estado.label}}</label>
                            {{form.estado}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
        </form>
    </div>
</div>

{% block content_extra_js %}

<script>



    $(function () {
        $('#id_custodio').select2();
   


    });

</script>
<script>
    $(function () {
        $('.select').select2(
            { theme: "bootstrap4", }
        );
    });


</script>
{% endblock content_extra_js %}

mies/templates/custodia/custodia_eliminar.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'custodia_eliminar' object.id %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          ¿Estás seguro que desea eliminar el registro: " Custodio: {{ object.custodio }} Equipo: {{ object.equipo }}"?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Si, Eliminar</button>
  
        </div>
    </div>
    </form>
  </div>