mies/mies/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import views as usuario_views
from red import views as red_views
from empleado import views as empleado_views
from ubicacion import views as ubicacion_views
from practica import views as practica_views
from actividad import views as actividad_views
from capacitacion import views as capacitacion_views
from inventario import views as inventario_views
from custodia import views as custodia_views
from configuracion import views as configuracion_views
from django.conf import settings
from django.conf.urls.static import static
#400
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [

    path('admin/', admin.site.urls),
    #MENU PARA LOS USUARIOS
    path('', usuario_views.dashboard_view.as_view(), name="dashboard") ,
   
    #MODULO OTROS
    # ACCESO A REDES  
    path('AccesoRed', red_views.AccesoRedListView.as_view(), name="accesoRed_listar") ,
    path('AccesoRed/Crear', red_views.AccesoRedCreateView.as_view(), name="accesoRed_crear") ,
    path('AccesoRed/Excel', red_views.AccesoRedExcelListView.as_view(), name="accesoRedExcel_crear") ,
    path('AccesoRed/Editar/<int:pk>', red_views.AccesoRedUpdateView.as_view(), name="accesoRed_editar") ,
    path('AccesoRed/Eliminar/<int:pk>', red_views.AccesoRedDeleteView.as_view(), name="accesoRed_eliminar") ,
    path('AccesoRed/Detalle/<int:pk>', red_views.AccesoRedDetailView.as_view(), name="accesoRed_detalle") ,
    #MODULO DE EMPLEADO
    #-- empleado
    path('Empleado', empleado_views.EmpleadoListView.as_view(), name="empleado_listar") ,
    path('Empleado/Crear', empleado_views.EmpleadoCreateView.as_view(), name="empleado_crear") ,
    path('Empleado/Excel', empleado_views.EmpleadoExcelListView.as_view(), name="empleadoExcel_crear") ,
    path('Empleado/Editar/<int:pk>', empleado_views.EmpleadoUpdateView.as_view(), name="empleado_editar") ,
    path('Empleado/Eliminar/<int:pk>', empleado_views.EmpleadoDeleteView.as_view(), name="empleado_eliminar") ,
    path('Empleado/Detalle/<int:pk>', empleado_views.EmpleadoDetailView.as_view(), name="empleado_detalle") ,
    #--area
    path('Area', empleado_views.AreaListView.as_view(), name="area_listar") ,
    path('Area/Crear', empleado_views.AreaCreateView.as_view(), name="area_crear") ,
    path('Area/Editar/<int:pk>', empleado_views.AreaUpdateView.as_view(), name="area_editar") ,
    path('Area/Eliminar/<int:pk>', empleado_views.AreaDeleteView.as_view(), name="area_eliminar") ,
    path('Area/Detalle/<int:pk>', empleado_views.AreaDetailView.as_view(), name="area_detalle") ,
    #--cargo
    path('Cargo', empleado_views.CargoListView.as_view(), name="cargo_listar") ,
    path('Cargo/Crear', empleado_views.CargoCreateView.as_view(), name="cargo_crear") ,
    path('Cargo/Editar/<int:pk>', empleado_views.CargoUpdateView.as_view(), name="cargo_editar") ,
    path('Cargo/Eliminar/<int:pk>', empleado_views.CargoDeleteView.as_view(), name="cargo_eliminar") ,
    path('Cargo/Detalle/<int:pk>', empleado_views.CargoDetailView.as_view(), name="cargo_detalle") ,
    #--unidad de atencion
    path('UnidadAtencion', empleado_views.UnidadListView.as_view(), name="unidad_listar") ,
    path('UnidadAtencion/Crear', empleado_views.UnidadCreateView.as_view(), name="unidad_crear") ,
    path('UnidadAtencion/Editar/<int:pk>', empleado_views.UnidadUpdateView.as_view(), name="unidad_editar") ,
    path('UnidadAtencion/Eliminar/<int:pk>', empleado_views.UnidadDeleteView.as_view(), name="unidad_eliminar") ,
    path('UnidadAtencion/Detalle/<int:pk>', empleado_views.UnidadDetailView.as_view(), name="unidad_detalle") ,
    #MODULO UBICACION DISTRITAL
    #--zona
    path('Zona', ubicacion_views.ZonaListView.as_view(), name="zona_listar") ,
    path('Zona/Crear', ubicacion_views.ZonaCreateView.as_view(), name="zona_crear") ,
    path('Zona/Editar/<int:pk>', ubicacion_views.ZonaUpdateView.as_view(), name="zona_editar") ,
    path('Zona/Eliminar/<int:pk>', ubicacion_views.ZonaDeleteView.as_view(), name="zona_eliminar") ,
    path('Zona/Detalle/<int:pk>', ubicacion_views.ZonaDetailView.as_view(), name="zona_detalle") ,
    #--provincia
    path('Provincia', ubicacion_views.ProvinciaListView.as_view(), name="provincia_listar") ,
    path('Provincia/Crear', ubicacion_views.ProvinciaCreateView.as_view(), name="provincia_crear") ,
    path('Provincia/Editar/<int:pk>', ubicacion_views.ProvinciaUpdateView.as_view(), name="provincia_editar") ,
    path('Provincia/Eliminar/<int:pk>', ubicacion_views.ProvinciaDeleteView.as_view(), name="provincia_eliminar") ,
    path('Provincia/Detalle/<int:pk>', ubicacion_views.ProvinciaDetailView.as_view(), name="provincia_detalle") ,
    #--distrito
    path('Distrito', ubicacion_views.DistritoListView.as_view(), name="distrito_listar") ,
    path('Distrito/Crear', ubicacion_views.DistritoCreateView.as_view(), name="distrito_crear") ,
    path('Distrito/Editar/<int:pk>', ubicacion_views.DistritoUpdateView.as_view(), name="distrito_editar") ,
    path('Distrito/Eliminar/<int:pk>', ubicacion_views.DistritoDeleteView.as_view(), name="distrito_eliminar") ,
    path('Distrito/Detalle/<int:pk>', ubicacion_views.DistritoDetailView.as_view(), name="distrito_detalle") ,
    #MODULO PRACTICAS PROFESIONALIZANTES
    #--Pasante
    path('Pasante', practica_views.PasanteListView.as_view(), name="pasante_listar") ,
    path('Pasante/Crear', practica_views.PasanteCreateView.as_view(), name="pasante_crear") ,
    path('Pasante/Excel', practica_views.PasanteExcelListView.as_view(), name="pasanteExcel_crear") ,
    path('Pasante/Editar/<int:pk>', practica_views.PasanteUpdateView.as_view(), name="pasante_editar") ,
    path('Pasante/Eliminar/<int:pk>', practica_views.PasanteDeleteView.as_view(), name="pasante_eliminar") ,
    path('Pasante/Detalle/<int:pk>', practica_views.PasanteDetailView.as_view(), name="pasante_detalle") ,
    #--Carrera
    path('Carrera', practica_views.CarreraListView.as_view(), name="carrera_listar") ,
    path('Carrera/Crear', practica_views.CarreraCreateView.as_view(), name="carrera_crear") ,
    path('Carrera/Editar/<int:pk>', practica_views.CarreraUpdateView.as_view(), name="carrera_editar") ,
    path('Carrera/Eliminar/<int:pk>', practica_views.CarreraDeleteView.as_view(), name="carrera_eliminar") ,
    path('Carrera/Detalle/<int:pk>', practica_views.CarreraDetailView.as_view(), name="carrera_detalle") ,
    #--Universidad
    path('Universidad', practica_views.UniversidadListView.as_view(), name="universidad_listar") ,
    path('Universidad/Crear', practica_views.UniversidadCreateView.as_view(), name="universidad_crear") ,
    path('Universidad/Editar/<int:pk>', practica_views.UniversidadUpdateView.as_view(), name="universidad_editar") ,
    path('Universidad/Eliminar/<int:pk>', practica_views.UniversidadDeleteView.as_view(), name="universidad_eliminar") ,
    path('Universidad/Detalle/<int:pk>', practica_views.UniversidadDetailView.as_view(), name="universidad_detalle") ,
    

    #MODULO ACTIVIDAD
    #--Actividad
    path('Actividad', actividad_views.ActividadListView.as_view(), name="actividad_listar"),
    path('Actividad/Crear',actividad_views.ActividadCreateView.as_view(),name ="actividad_crear"),
    path('Actividad/pdf/<int:pk>', actividad_views.ActividadReportePdfDetailView.as_view(), name="actividad_reporte_pdf") ,
    path('Actividad/Editar/<int:pk>',actividad_views.ActividadUpdateView.as_view(),name ="actividad_editar"),
    path('Actividad/Eliminar/<int:pk>',actividad_views.ActividadDeleteView.as_view(),name ="actividad_eliminar"),
    path('Actividad/Detalle/<int:pk>',actividad_views.ActividadDetailView.as_view(),name ="actividad_detalle"),
   
    #--Asunto
    path('Asunto', actividad_views.AsuntoListView.as_view(), name="asunto_listar"),
    path('Asunto/Crear',actividad_views.AsuntoCreateView.as_view(),name ="asunto_crear"),
    path('Asunto/Editar/<int:pk>',actividad_views.AsuntoUpdateView.as_view(),name ="asunto_editar"),
    path('Asunto/Eliminar/<int:pk>',actividad_views.AsuntoDeleteView.as_view(),name ="asunto_eliminar"),
    path('Asunto/Detalle/<int:pk>',actividad_views.AsuntoDetailView.as_view(),name ="asunto_detalle"),

     #--Capacitacion
    path('Capacitacion', capacitacion_views.CapacitacionListView.as_view(), name="capacitacion_listar") ,
    path('Capacitacion/Crear', capacitacion_views.CapacitacionCreateView.as_view(), name="capacitacion_crear") ,
    path('Capacitacion/Editar/<int:pk>', capacitacion_views.CapacitacionUpdateView.as_view(), name="capacitacion_editar") ,
    path('Capacitacion/Eliminar/<int:pk>', capacitacion_views.CapacitacionDeleteView.as_view(), name="capacitacion_eliminar") ,
    path('Capacitacion/Detalle/<int:pk>', capacitacion_views.CapacitacionDetailView.as_view(), name="capacitacion_detalle") ,
    path('Capacitacion/pdf/<int:pk>', capacitacion_views.CapacitacionReportePdfDetailView.as_view(), name="capacitacion_reporte_pdf") ,


    #Modulo Inventario 
    #--Marca
    path('Marca', inventario_views.MarcaListView.as_view(), name="marca_listar"),
    path('Marca/Crear',inventario_views.MarcaCreateView.as_view(),name ="marca_crear"),
    path('Marca/Editar/<int:pk>',inventario_views.MarcaUpdateView.as_view(),name ="marca_editar"),
    path('Marca/Eliminar/<int:pk>',inventario_views.MarcaDeleteView.as_view(),name ="marca_eliminar"),
    path('Marca/Detalle/<int:pk>',inventario_views.MarcaDetailView.as_view(),name ="marca_detalle"),
    #--Modelo
    path('Modelo', inventario_views.ModeloListView.as_view(), name="modelo_listar"),
    path('Modelo/Crear',inventario_views.ModeloCreateView.as_view(),name ="modelo_crear"),
    path('Modelo/Editar/<int:pk>',inventario_views.ModeloUpdateView.as_view(),name ="modelo_editar"),
    path('Modelo/Eliminar/<int:pk>',inventario_views.ModeloDeleteView.as_view(),name ="modelo_eliminar"),
    path('Modelo/Detalle/<int:pk>',inventario_views.ModeloDetailView.as_view(),name ="modelo_detalle"),

mies/actividad/models.py
from django.db import models
from empleado.models import Area, Empleado
from configuracion.models import Configuracion

class Asunto(models.Model):
    """Model definition for Asunto."""

    
    descripcion = models.CharField('Asunto', max_length=50, unique =True)

    class Meta:
        """Meta definition for Asunto."""

        verbose_name = 'Asunto'
        verbose_name_plural = 'Asuntos'

    def __str__(self):
        """Unicode representation of Asunto."""
        return self.descripcion

    def save(self,*args, **kwargs):
        """Save method for Asunto."""
        self.descripcion = self.descripcion and (self.descripcion).upper()
        return super(Asunto, self).save(*args, **kwargs)


class ActividadCabecera(models.Model):
    """Model definition for ActividadCabecera."""

    fecha = models.DateField('Fecha', auto_now=False, auto_now_add=False)
    responsable = models.ForeignKey(Configuracion, on_delete=models.PROTECT,related_name='responsable_de_actividad')
    usuario = models.ForeignKey(Empleado, on_delete=models.PROTECT)
    ubicacion = models.ForeignKey(Area,verbose_name='Ubicación', on_delete=models.PROTECT)
    lista_tipo_prioridad = [
    ('1', 'ALTA'),
    ('2', 'MEDIA'),
    ('3', 'BAJA'),]
    prioridad = models.CharField('Prioridad',max_length=1, choices=lista_tipo_prioridad, default='1')

    observacion = models.TextField('Observación', null= True , blank = True)
    class Meta:
        """Meta definition for ActividadCabecera."""

        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades '

    def __int__(self):
        """Unicode representation of ActividadCabecera."""
        return self.fecha
    def save(self,*args, **kwargs):
        """Save method for ActividadCabecera."""
        self.observacion = self.observacion and (self.observacion).upper()
        return super(ActividadCabecera, self).save(*args, **kwargs)

 

class ActividadDetalle(models.Model):
    """Model definition for ActividadDetalle."""
    cabeceraActividad = models.ForeignKey(ActividadCabecera, on_delete=models.CASCADE)
    asunto =models.ForeignKey(Asunto, on_delete=models.PROTECT)

    class Meta:
        """Meta definition for ActividadDetalle."""

        verbose_name = 'Actividad Detalle'
        verbose_name_plural = 'Actividad Detalles'

    def __int__(self):
        """Unicode representation of ActividadDetalle."""
        return self.asunto

mies/actividad/forms.py
from django import forms
from .models import  Asunto, ActividadCabecera, ActividadDetalle
from django.forms.models import inlineformset_factory


class AsuntoForm(forms.ModelForm):

  
     #validaciones para que se envie como mayusculas los datos
    def clean_descripcion(self):
        data = self.cleaned_data["descripcion"].upper()
        return data
    def clean_observacion(self):
        data = self.cleaned_data["observacion"].upper()
        return data   
    class Meta:
        model = Asunto
        fields = ('descripcion',)

        widgets = {
            'descripcion': forms.TextInput(
                attrs={
                    'class': 'form-control solo-letra',
                        'autofocus':'autofocus'
                }
            ),
        }

class ActividadCabeceraForm(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['responsable'].empty_label = "------N/A--------"
        self.fields['usuario'].empty_label = "------N/A--------"
        self.fields['ubicacion'].empty_label = "------N/A--------"    
    
    class Meta:
        model = ActividadCabecera
        fields = (
        'fecha',
        'responsable',
        'usuario',
        'ubicacion',
        'prioridad',
        'observacion',)

        widgets = {
            'fecha':forms.DateInput(format=('%Y-%m-%d'),
                attrs={
                    'type':'date',
                    'class': 'form-control',
                        'autofocus':'autofocus'
                }
            ),
            'responsable':forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'usuario':forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'ubicacion': forms.Select(
                attrs={
                    'class': 'form-control select',
                }
            ),
            'prioridad':forms.Select(
                attrs={
                    'class': 'form-control select'
                }
            ),
            'observacion':forms.Textarea(
                attrs={
                    
                    'class': 'form-control',
                    "rows":3, "cols":10
                }
            ),
        }

class ActividadDetalleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['asunto'].empty_label = "------N/A--------"
    class Meta:
        model = ActividadDetalle
        fields = ('cabeceraActividad',
                   'asunto',)

        widgets = {
            'cabeceraActividad': forms.Select(
                attrs ={
                    'class': 'form-control'
                }
            ),
            'asunto': forms.Select(
                attrs ={
                    'class': 'form-control select',
                        'autofocus':'autofocus'
                }
            ),
        }

ActividadCabDetalleForm = inlineformset_factory(ActividadCabecera,ActividadDetalle,form=ActividadDetalleForm, extra=1,can_delete= True)

mies/templates/actividad/actividad_crear.html
{% extends 'base_generic.html' %}
{% block title %}NUEVO ACTIVIDAD{% endblock %}


{% block content_main %}
<!-- Page Heading -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'actividad_listar' %}">Actividad</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
    </ol>
</nav>
<div class="container">

    {% if form.errors %}

    <div class="alert alert-danger" role="alert">
        <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                <li>
                    {{error}}
                </li>
                {% endfor %}
            {% endfor %}
        </ul>

    </div>
    {% endif %}

    <span class="border border-light">

        <form method="post" >
            {% csrf_token %}
            <h4>Información de la Actividad.</h4>
            
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="id_ubicacion">{{form.ubicacion.label}}*</label>
                        {{form.ubicacion}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_prioridad">{{form.prioridad.label}}*</label>
                        {{form.prioridad}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_fecha">{{form.fecha.label}}*</label>
                        {{form.fecha}}
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col">
                    <div class="form-group">
                       <label for="id_responsable"> {{form.responsable.label}}*</label>
                        {{form.responsable}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_usuario">{{form.usuario.label}}*</label>
                        {{form.usuario}}
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <label for="id_observacion">{{form.observacion.label}}</label>
                {{form.observacion}}
            </div>
           
            <h4>Actividad Detalles.</h4>
           
            <div id="jsTotalForms"  class="form-row">
                {{detalle_form.management_form}}
                {% for form1 in detalle_form %}
               
                <div id='js_periferico' class="form-group col-md-10">
                    {{form1.asunto.label}}
                    {{form1.asunto}}
                </div>

                <div id='js_eliminar' class="form-group col-md-2">
                    {{form1.DELETE.label}}
                    {{form1.DELETE}}
                </div>
                {% endfor %}

            </div>
            <button class="button form-control col-md-4" type='button' onclick="agregar_inputs();">Agregar</button>

            <fieldset class="modal-footer">
                <a type="button" class="btn btn-secondary" href="{% url 'actividad_listar' %}">Cancelar</a>
                <button type="submit" class="btn  btn-primary">Guardar Registro</button>
            </fieldset>
        </form>
    </span>
    
</div>

{% endblock %}


{% block content_extra_js %}


<script>
    
    function agregar_inputs(){
        $('.select').select2("destroy");
        var total_forms = document.querySelectorAll('#jsTotalForms input[type=hidden]')[0];
        
        var value_last = parseInt(total_forms.value)-1;
        //nuevo label e input para periferico
        var nuevo_label_periferico = document.createElement('label');
        nuevo_label_periferico.innerHTML = 'Empleado'
        var nuevo_select_periferico = document.querySelector('#id_actividaddetalle_set-'+ value_last + '-asunto').cloneNode(true);
        nuevo_select_periferico.name = 'actividaddetalle_set-'+total_forms.value+'-asunto';
        nuevo_select_periferico.id = 'id_actividaddetalle_set-'+total_forms.value+'-asunto';
        nuevo_select_periferico.className = 'form-control select'
        //nuevo label e input para eliminar
        var nuevo_label_eliminar = document.createElement('label');
        nuevo_label_eliminar.innerHTML = 'Eliminar'
        nuevo_label_eliminar.className = 'col-md-12'
        nuevo_label_eliminar.style.top = "40px"
        nuevo_label_eliminar.style.bottom = "40px"
        var nuevo_select_eliminar = document.querySelector('#id_actividaddetalle_set-'+value_last+'-DELETE').cloneNode(true);
        nuevo_select_eliminar.name = 'actividaddetalle_set-'+total_forms.value+'-DELETE';
        nuevo_select_eliminar.id = 'id_actividaddetalle_set-'+total_forms.value+'-DELETE';
        nuevo_select_eliminar.className = ' col-md-12'
        nuevo_select_eliminar.style.top = "40px"
        nuevo_select_eliminar.style.bottom = "40px"

        var cantidadElemen = document.querySelectorAll("#js_periferico");
        var cantidadElemen_eliminar = document.querySelectorAll("#js_eliminar");

        for (let i=0; i< cantidadElemen.length; i++){
            if (i == cantidadElemen.length-1){
                cantidadElemen[i].appendChild(nuevo_label_periferico);
                cantidadElemen[i].appendChild(nuevo_select_periferico);
                cantidadElemen_eliminar[i].appendChild(nuevo_label_eliminar);
                cantidadElemen_eliminar[i].appendChild(nuevo_select_eliminar);
            }
        }
        total_forms.value = parseInt(total_forms.value)+1;
    
        $(function () {
            $('.select').select2(
                { theme: "bootstrap4", }
            );
        });
    }
</script>
{% endblock content_extra_js %}

mies/templates/actividad/actividad_editar.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar Registro</h5>
           
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          
  
        </div>
        {% if form.errors %}
  
        <div class="alert alert-danger" role="alert">
            <h5 class="icon fas fa-bin">Error al guardar el registro!</h5>
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                    <li>
                        {{error}}
                    </li>
                    {% endfor %}
                {% endfor %}
            </ul>
  
        </div>
        {% endif %}
        
        
        
        <form action="{% url 'actividad_editar' object.id %}" method="post">
            {% csrf_token %}
               
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="id_ubicacion">{{form.ubicacion.label}}*</label>
                        {{form.ubicacion}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_prioridad">{{form.prioridad.label}}*</label>
                        {{form.prioridad}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_fecha">{{form.fecha.label}}*</label>
                        {{form.fecha}}
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col">
                    <div class="form-group">
                       <label for="id_responsable"> {{form.responsable.label}}*</label>
                        {{form.responsable}}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="id_usuario">{{form.usuario.label}}*</label>
                        {{form.usuario}}
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <label for="id_observacion">{{form.observacion.label}}</label>
                {{form.observacion}}
            </div>
           
            <h4>Actividad Detalles.</h4>

            <div class="form-row">                        
                {{detalle_form.management_form}}
                {% for form1 in detalle_form %}
                {{form1.id}}
                <div id = 'js_periferico' class="form-group col-md-6">
                    {{form1.asunto.label}}
                    {{form1.asunto}}
                </div>
                <div id = 'js_eliminar'  class="form-group col-md-2">
                    {{form1.DELETE.label}}
                    {{form1.DELETE}}
                </div>
                {% endfor %}
            </div>
            <button class="button form-control col-md-4" type='button' onclick="agregar_inputs();">Agregar Periferico</button>
        

          
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </div>
        </form>
    </div>
  </div>

  


  {% block content_extra_js %}
  <script>
      $(function(){
          $('#id_tipoDocumento').select2();
          $('#id_responsable').select2();
          $('#id_usuario').select2();
      });
  </script>
  <script>
    $(function () {
        $('.select').select2(
            { theme: "bootstrap4", }
        );
    });


</script>
  
  <script>
      function agregar_inputs(){
          var total_forms = document.querySelector('#id_actividaddetalle_set-TOTAL_FORMS');
          var value_last = parseInt(total_forms.value)-1;
          //nuevo label e input para periferico
          var nuevo_label_periferico = document.createElement('label');
          nuevo_label_periferico.innerHTML = 'Asunto'
          var nuevo_select_periferico = document.querySelector('#id_actividaddetalle_set-0-asunto').cloneNode(true);
          var span_periferico = document.querySelector(".select2").cloneNode(true);
          nuevo_select_periferico.name = 'actividaddetalle_set-'+total_forms.value+'-asunto';
          nuevo_select_periferico.id = 'id_actividaddetalle_set-'+total_forms.value+'-asunto';
        //
          var span_periferico = document.querySelector(".select2").cloneNode(true);
          document.querySelector('#js_periferico').appendChild(nuevo_label_periferico);
          document.querySelector('#js_periferico').appendChild(nuevo_select_periferico);
          total_forms.value = parseInt(total_forms.value)+1;
          //nuevo label e input para eliminar
          var nuevo_label_eliminar = document.createElement('label');
          nuevo_label_eliminar.innerHTML = 'Eliminar'
          var nuevo_select_eliminar = document.querySelector('#id_actividaddetalle_set-'+value_last+'-DELETE').cloneNode(true);
          nuevo_select_eliminar.name = 'actividaddetalle_set-'+total_forms.value+'-DELETE';
          nuevo_select_eliminar.id = 'id_actividaddetalle_set-'+total_forms.value+'-DELETE';
          document.querySelector('#js_eliminar').appendChild(nuevo_label_eliminar);
          document.querySelector('#js_eliminar').appendChild(nuevo_select_eliminar);
          total_forms.value = parseInt(total_forms.value)+1;
      }

      
  </script>
  {% endblock content_extra_js %}
  

mies/templates/actividad/actividad_eliminar.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'actividad_eliminar' object.id %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          ¿Estás seguro que desea eliminar el registro: "{{ object.fecha }} {{ object.usuario }}"?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Si, Eliminar</button>
  
        </div>
    </div>
    </form>
  </div>